# Generated by Django 4.0.6 on 2022-08-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortalJobsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_dt', models.DateTimeField(auto_now=True)),
                ('job_template_name', models.CharField(max_length=200, verbose_name='Шаблон')),
                ('job_template_keys', models.CharField(max_length=200, verbose_name='Учетные данные')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
            },
        ),
    ]
