# Generated by Django 4.0.6 on 2022-08-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortalFrontSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaphore_srv_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('semaphore_srv_address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('semaphore_srv_user', models.CharField(max_length=200, verbose_name='Пользователь')),
                ('semaphore_srv_priv_key_file', models.CharField(max_length=200, verbose_name='Приватный ключ')),
                ('semaphore_srv_operator_dir', models.CharField(max_length=200, verbose_name='Папка c файлами')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
