# Generated by Django 4.0.6 on 2022-08-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalfrontsettings',
            name='copy_files_program',
            field=models.CharField(default=1, max_length=200, verbose_name='ПО для копирования'),
            preserve_default=False,
        ),
    ]
