# Generated by Django 4.0.6 on 2022-08-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_front', '0004_alter_note_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Заметки', 'verbose_name_plural': 'Заметка'},
        ),
        migrations.AddField(
            model_name='note',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
