# Generated by Django 4.0.6 on 2022-08-17 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_front', '0005_alter_note_options_note_name_alter_note_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
    ]
