# Generated by Django 4.0.6 on 2022-08-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_front', '0006_alter_note_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalGlpiSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glpi_api_url', models.CharField(max_length=200, verbose_name='api url')),
                ('glpi_user_token', models.CharField(max_length=200, verbose_name='user token')),
                ('glpi_app_token', models.CharField(max_length=200, verbose_name='app token')),
            ],
        ),
    ]
