# Generated by Django 4.0.6 on 2022-08-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_front', '0008_alter_portalfrontsettings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSemaphoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaphore_srv_name', models.CharField(max_length=200, null=True, verbose_name='Имя')),
                ('semaphore_api_url', models.CharField(max_length=200, verbose_name='api url')),
                ('semaphore_user_login', models.CharField(max_length=200, verbose_name='user login')),
                ('semaphore_user_password', models.CharField(max_length=200, verbose_name='user password')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки SEMAPHORE API',
            },
        ),
    ]
