# Generated by Django 4.0.6 on 2022-08-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_front', '0009_portalsemaphoresettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalsemaphoresettings',
            name='semaphore_user_token',
            field=models.CharField(max_length=200, null=True, verbose_name='user_token'),
        ),
    ]
